name: Create terraform plan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_ACTION_WORKING_DIR: '.'
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    defaults:
      run:
        working-directory: ${{ env.TF_ACTION_WORKING_DIR }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Create Profile
      id: profile
      run: touch credentials
         | echo  ${{ secrets.AWS_SESSION_TOKEN }} > credentials
         | echo  ${{ secrets.AWS_SECRET_ACCESS_KEY }} > credentials
         | echo  ${{ secrets.AWS_ACCESS_KEY_ID }} > credentials
         | echo '[default]'  > credentials
         | cat credentials
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
   
